name: Release to NuGet

on:
  release:
    types: [published]

env:
  EXTENDEDDISTRIBUTEDCACHEPROJECTNAME: "ModCaches.ExtendedDistributedCache"
  ORLEANSCACHESPROJECTNAME: "ModCaches.OrleansCaches"
  
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: | 
          8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build - Extended Distributed Cache
      run: dotnet build ${{ env.EXTENDEDDISTRIBUTEDCACHEPROJECTNAME }} --configuration Release --no-restore
      working-directory: src
    - name: Build - Orleans Caches
      run: dotnet build ${{ env.ORLEANSCACHESPROJECTNAME }} --configuration Release --no-restore
      working-directory: src

    - name: Package nuget - Extended Distributed Cache
      run: dotnet pack ${{ env.EXTENDEDDISTRIBUTEDCACHEPROJECTNAME }} --configuration Release --no-build -o:package
      working-directory: src
    - name: Package nuget - Orleans Caches
      run: dotnet pack ${{ env.ORLEANSCACHESPROJECTNAME }} --configuration Release --no-build -o:package
      working-directory: src

    - name: Push to NuGet
      run: dotnet nuget push ./package/*.nupkg --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json
      working-directory: src
